steps:
- checkout: self
  fetchDepth: 1
  displayName: 'Checkout repository'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install npm dependencies'

- script: npm run build
  displayName: 'Build React Vite project'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-myfrontend-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload-batch \
        --account-name ichmahesh123 \
        --destination '$web' \
        --source $(buildDir) \
        --overwrite
  displayName: 'Deploy to Azure Blob Storage'
